FROM ubuntu:23.04
# USER ubuntu

SHELL ["/bin/bash", "-c"]

RUN apt -y update && apt -y upgrade

RUN apt-get -y install software-properties-common && \
apt-get -y install nodejs npm && \
apt-get -y install wget

# install MongoSH:
RUN wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add -
RUN echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list
RUN apt -y update && \
apt-get install -y mongodb-mongosh

RUN mkdir /home/ubuntu/myapp

RUN npm install -g nodemon live-server

WORKDIR /home/ubuntu/myapp

# ENTRYPOINT [/bin/bash]
ENTRYPOINT ["tail", "-f", "/dev/null"]